-- Independent integration checks against GDD; deterministic, memory-only persistence.
local Game=require('src.game')
local Deck=require('src.deck')
local Persist=require('src.persist')
local pass,errors=0,{}
local function check(n,fn) local ok,e=pcall(fn);if ok then pass=pass+1;print('PASS '..n) else errors[#errors+1]=n..': '..tostring(e);print('FAIL '..errors[#errors]) end end
local function eq(a,b) assert(a==b,tostring(a)..' ~= '..tostring(b)) end
local function c(r,v) return {rank=tostring(r),value=v,suit='S',kind='basic',is_basic=true} end
local function new()
 local files={};local fs={read=function(p)return files[p]end,write=function(p,v)files[p]=v;return true end,mkdir=function()return true end,getInfo=function(p)return files[p] and {type='file'}end}
 return Game.new({filesystem=fs}),files
end
check('Stage one does not clear before its scheduled final round',function()
 local g=new();local s=g.state;s.stage=1;s.stageTarget=2000;s.chips=2500;s.roundsInStage=1;s.stageRounds=15;g._g:scheduleAfterRound();assert(s.afterResult~='stageClear' and s.afterResult~='victory')
end)
check('Stage one clears at round fifteen when solvent',function()
 local g=new();local s=g.state;s.stage=1;s.stageTarget=2000;s.chips=2500;s.roundsInStage=15;s.stageRounds=15;g._g:scheduleAfterRound();eq(s.afterResult,'stageClear')
end)
check('Stage two eliminates insufficient chips at deadline',function()
 local g=new();local s=g.state;s.stage=2;s.stageTarget=20000;s.chips=19000;s.roundsInStage=15;s.stageRounds=15;g._g:scheduleAfterRound();eq(s.afterResult,'forceExit')
end)
check('Stage three can clear before thirty rounds',function()
 local g=new();local s=g.state;s.stage=3;s.stageTarget=2000000;s.chips=2000000;s.roundsInStage=1;s.stageRounds=30;g._g:scheduleAfterRound();assert(s.afterResult=='stageClear' or s.afterResult=='victory')
end)
check('Disabling automatic bankruptcy preserves debt play',function()
 local g=new();local s=g.state;s.settings.autoEndOnBroke=false;s.chips=-100;s.roundsInStage=1;g._g:scheduleAfterRound();assert(s.afterResult~='forceExit')
end)
check('Assassin does not disable non-reading cheats',function()
 local g=new();g.state.stage=2;g.state.playerClass={id='assassin'};eq(g._g:cheatChance(),0.2)
end)
check('Deep draw selects needed four and preserves top card',function()
 local g=new();local s=g.state;s.dealer.hand={c(10),c(7)};s.dealer.total=17;s.deck=Deck.new();s.deck:addCards({c(9),c(4),c(2)});local uid=s.deck.drawPile[1].uid;s.cheatIntent={move='D',pending=true,executed=false};g._g:dealerDrawOne();eq(s.dealer.hand[3].rank,'4');eq(s.deck.drawPile[1].uid,uid);eq(#s.deck.discardPile,0);assert(s.cheatIntent.executed)
end)
check('False accusation ends player turn',function()
 local g=new();local s=g.state;s.state='player';s.bet=100;s.player.hand={c(10),c(7)};s.dealer.hand={c(10),c(8)};s.cheatIntent={executed=false};assert(g:action('accuse'));assert(s.state~='player');g:flush();assert(s.state=='result' or s.state=='forceExit')
end)
check('Dealer-turn accusation interrupts pending drawing',function()
 local g=new();local s=g.state;s.state='dealer';s.bet=100;s.cheatIntent={executed=true};s.player.hand={c(10),c(7)};s.dealer.hand={c(10),c(8)};local triggered=false;g._g:after(1,function()triggered=true end);assert(g:action('accuse'));g:flush();assert(not triggered,'stale dealer queue executed');assert(s.result and s.result.outcome=='player')
end)
check('Persistence surfaces a backend write rejection',function()
 local p=Persist.new({fs={write=function()return false,'disk full'end,mkdir=function()return true end}});local ok=p:writeProgress(Persist.defaultProgress());eq(ok,false)
end)
check('Corrupted progress falls back to sanitized defaults',function()
 local p=Persist.new({fs={read=function()return 'not lua !'end}});local state,loaded=p:readProgress();eq(loaded,false);assert(type(state.meta)=='table' and type(state.settings)=='table')
end)
check('Normal start and relic selection enter betting',function()
 local g=new();assert(g:start('normal',1234));eq(g.state.state,'relic_select');assert(g:action('pick_relic',1));eq(g.state.state,'bet');assert(g:action('bet_set',100));assert(g:action('bet_confirm'));g:flush();assert(g.state.state=='player' or g.state.state=='result')
end)
check('Null draw is handled without a card crash',function()
 local g=new();eq(g._g:pushHand('player',nil),false)
end)
check('Black hole keeps own identity while inheriting previous traits',function()
 local g=new();local s=g.state;local prior=c(6);prior.is_67=true;prior.s67_rank='6';prior.mult_bonus=0.5;local hole=c(8);hole.is_blackhole=true;s.deck:addCards({prior,hole});local a=s.deck:draw();local b=s.deck:draw();local uid=b.uid;g._g:pushHand('player',a);g._g:pushHand('player',b);eq(#s.player.hand,1);eq(s.player.hand[1].uid,uid);assert(s.player.hand[1].is_blackhole and s.player.hand[1].is_67);eq(s.player.hand[1].mult_bonus,0.5);eq(#s.deck.discardPile,1)
end)
check('Berserker only tolerates totals up to twenty five',function()
 local g=new();local s=g.state;s.playerClass={id='berserker'};s.player.hand={c(10),c(10),c(5)};g._g:refreshPlayer();eq(s.player.busted,false);s.player.hand[3]=c(6);g._g:refreshPlayer();eq(s.player.busted,true)
end)
local SI=require('src.shoe_info')
local function quote(prob)
 local g=new();local s=g.state;s.dealer.hand={c(10),c(6)};s.bustBet={on=true,locked=true,amount=50};local orig=SI.dealerBustOdds;SI.dealerBustOdds=function()return prob,{reason='budget_exceeded',coverageGap='budget'}end;local ok,err=pcall(function()g._g:lockBustBetOdds()end);SI.dealerBustOdds=orig;assert(ok,err);return s.bustBet
end
check('Certain dealer bust quotes minimum odds',function() local q=quote(1);eq(q.prob,1);eq(q.odds,1.2)end)
check('Impossible dealer bust quotes capped odds',function()local q=quote(0);eq(q.prob,0);eq(q.odds,8)end)
check('Budget exhaustion produces unknown quote not invented probability',function()local q=quote(nil);eq(q.prob,nil);eq(q.unknown,true);eq(q.odds,8)end)
print(string.format('Flow acceptance: PASS=%d FAIL=%d',pass,#errors));if #errors>0 then error(table.concat(errors,'\n'))end
