-- src/cocktails.lua 34 款调酒（附录 D）
-- 每款一个主动技能：喝 1 口解锁 5 小局，每小局限用 1 次；ability.special 由 bar_mode 分发。
-- 技能文本、交互类型、作用对象严格取自 GDD 附录 D；基酒/原料为表现用补充。
local C = {}
C.LIST = {
  { id='ck_mercury', gddId='mercury', name='莫斯科骡子', en='Moscow Mule', glass='copper', base='vodka', baseName='伏特加', ingredients={'伏特加'}, color={r=0.85,g=0.6,b=0.2}, strength=2, gift=true, group='base', ability={ id='ab_mercury', name='重洗', desc='弃掉你全部手牌，再抽等量张新牌', target='自己手牌+牌堆', special='redraw_hand', interaction='instant', duration='round' } },
  { id='ck_venus', gddId='venus', name='大都会', en='Cosmopolitan', glass='martini', base='vodka', baseName='伏特加', ingredients={'伏特加'}, color={r=0.9,g=0.2,b=0.4}, strength=3, gift=true, group='base', ability={ id='ab_venus', name='换牌', desc='把你的一张手牌换成同种牌组的任意另一张', target='自己手牌+牌堆', special='swap_hand_card', interaction='two_step', duration='round' } },
  { id='ck_earth', gddId='earth', name='古典鸡尾酒', en='Old Fashioned', glass='rocks', base='whiskey', baseName='威士忌', ingredients={'威士忌'}, color={r=0.7,g=0.4,b=0.1}, strength=4, gift=true, group='base', ability={ id='ab_earth', name='透牌', desc='查看牌堆顶 3 张，可把其中任意张沉到牌堆底', target='牌堆', special='peek_sink_pick', interaction='checklist', duration='round' } },
  { id='ck_mars', gddId='mars', name='血腥玛丽', en='Bloody Mary', glass='highball', base='vodka', baseName='伏特加', ingredients={'伏特加'}, color={r=0.7,g=0.05,b=0.05}, strength=2, gift=true, group='base', ability={ id='ab_mars', name='着火', desc='烧掉本局牌堆的一半，只留下随机一半', target='牌堆', special='burn_half', interaction='instant', duration='round' } },
  { id='ck_jupiter', gddId='jupiter', name='迈泰', en='Mai Tai', glass='tiki', base='rum', baseName='朗姆', ingredients={'朗姆'}, color={r=0.95,g=0.5,b=0.2}, strength=3, gift=true, group='base', ability={ id='ab_jupiter', name='双份', desc='复制你点数最低的一张手牌，多拿一张', target='自己手牌', special='duplicate_lowest', interaction='instant', duration='round' } },
  { id='ck_saturn', gddId='saturn', name='新加坡司令', en='Singapore Sling', glass='hurricane', base='gin', baseName='金酒', ingredients={'金酒'}, color={r=0.9,g=0.3,b=0.3}, strength=2, gift=true, group='base', ability={ id='ab_saturn', name='封口', desc='酒保本局立即停牌，不再要牌', target='庄家', special='dealer_stop', interaction='instant', duration='round' } },
  { id='ck_uranus', gddId='uranus', name='蓝色泻湖', en='Blue Lagoon', glass='highball', base='vodka', baseName='伏特加', ingredients={'伏特加'}, color={r=0.1,g=0.5,b=0.9}, strength=2, gift=true, group='base', ability={ id='ab_uranus', name='加冰', desc='弃掉你点数最高的一张手牌', target='自己手牌', special='discard_highest', interaction='instant', duration='round' } },
  { id='ck_neptune', gddId='neptune', name='尼格罗尼', en='Negroni', glass='rocks', base='gin', baseName='金酒', ingredients={'金酒'}, color={r=0.8,g=0.15,b=0.1}, strength=4, gift=true, group='base', ability={ id='ab_neptune', name='掉包', desc='用你的一张手牌换走酒保的一张明牌', target='自己手牌↔庄家', special='swap_with_dealer', interaction='two_step', duration='round' } },
  { id='ck_pluto', gddId='pluto', name='黑暗风暴', en='Dark Storm', glass='rocks', base='rum', baseName='朗姆', ingredients={'朗姆'}, color={r=0.2,g=0.1,b=0.3}, strength=3, gift=true, group='base', ability={ id='ab_pluto', name='弃牌', desc='随机弃掉你的一张手牌', target='自己手牌', special='discard_random', interaction='instant', duration='round' } },
  { id='ck_planetx', gddId='planetx', name='泛银河系漱口酒', en='Pan Galactic Gargle Blaster', glass='highball', base='vodka', baseName='伏特加', ingredients={'伏特加'}, color={r=0.4,g=0.8,b=0.9}, strength=5, gift=true, group='base', ability={ id='ab_planetx', name='错乱', desc='从冠军牌组里挑一张，直接打进你的手牌', target='自己手牌←冠军牌组', special='pick_from_champion', interaction='pick_champion', duration='round' } },
  { id='ck_ceres', gddId='ceres', name='收获之月', en='Harvest Moon', glass='wine', base='sake', baseName='清酒', ingredients={'清酒'}, color={r=0.9,g=0.7,b=0.2}, strength=1, gift=true, group='base', ability={ id='ab_ceres', name='移花', desc='抽走酒保点数最大的一张明牌，沉到牌堆底', target='庄家+牌堆', special='take_dealer_highest_sink', interaction='instant', duration='round' } },
  { id='ck_eris', gddId='eris', name='金色黎明', en='Golden Dawn', glass='martini', base='gin', baseName='金酒', ingredients={'金酒'}, color={r=0.95,g=0.8,b=0.3}, strength=3, gift=true, group='base', ability={ id='ab_eris', name='弹走', desc='把你点数最小的一张手牌弹给酒保', target='自己手牌→庄家', special='give_lowest_to_dealer', interaction='instant', duration='round' } },
  { id='ck_fool', gddId='fool', name='长岛冰茶', en='Long Island Iced Tea', glass='highball', base='vodka', baseName='伏特加', ingredients={'伏特加'}, color={r=0.6,g=0.4,b=0.15}, strength=5, gift=false, group='tarot', ability={ id='ab_fool', name='胡闹', desc='把庄家最后一张明牌沉到牌堆底，并立即补发 1 张新明牌', target='A 改变庄家明牌数', special='dealer_last_sink_draw', interaction='instant', duration='round' } },
  { id='ck_magician', gddId='magician', name='马天尼', en='Martini', glass='martini', base='gin', baseName='金酒', ingredients={'金酒'}, color={r=0.95,g=0.95,b=0.85}, strength=4, gift=false, group='tarot', ability={ id='ab_magician', name='戏法', desc='为庄家额外发 1 张明牌', target='A 改变庄家明牌数', special='dealer_extra_up', interaction='instant', duration='round' } },
  { id='ck_high_priestess', gddId='high_priestess', name='白色佳人', en='White Lady', glass='martini', base='gin', baseName='金酒', ingredients={'金酒'}, color={r=0.95,g=0.95,b=0.9}, strength=3, gift=false, group='tarot', ability={ id='ab_high_priestess', name='低语', desc='把庄家点数最小的一张明牌沉底，并立即补发 1 张新明牌', target='A 改变庄家明牌数', special='dealer_lowest_sink_draw', interaction='instant', duration='round' } },
  { id='ck_empress', gddId='empress', name='贝里尼', en='Bellini', glass='flute', base='prosecco', baseName='普罗塞克', ingredients={'普罗塞克'}, color={r=0.95,g=0.6,b=0.4}, strength=1, gift=false, group='tarot', ability={ id='ab_empress', name='加冕', desc='若庄家明牌不足 2 张，补发到 2 张', target='A 改变庄家明牌数', special='dealer_fill_to_2', interaction='instant', duration='round' } },
  { id='ck_emperor', gddId='emperor', name='教父', en='Godfather', glass='rocks', base='whiskey', baseName='威士忌', ingredients={'威士忌'}, color={r=0.8,g=0.5,b=0.15}, strength=4, gift=false, group='tarot', ability={ id='ab_emperor', name='律令', desc='强制庄家立即抽 1 张明牌', target='B 强制庄家抽牌', special='dealer_draw_1', interaction='instant', duration='round' } },
  { id='ck_hierophant', gddId='hierophant', name='曼哈顿', en='Manhattan', glass='martini', base='whiskey', baseName='威士忌', ingredients={'威士忌'}, color={r=0.8,g=0.1,b=0.1}, strength=4, gift=false, group='tarot', ability={ id='ab_hierophant', name='布道', desc='强制庄家立即抽 2 张明牌', target='B 强制庄家抽牌', special='dealer_draw_2', interaction='instant', duration='round' } },
  { id='ck_lovers', gddId='lovers', name='含羞草', en='Mimosa', glass='flute', base='prosecco', baseName='普罗塞克', ingredients={'普罗塞克'}, color={r=0.95,g=0.7,b=0.3}, strength=1, gift=false, group='tarot', ability={ id='ab_lovers', name='结对', desc='复制庄家的最后一张明牌作为新明牌', target='A 改变庄家明牌数', special='dealer_copy_last', interaction='instant', duration='round' } },
  { id='ck_chariot', gddId='chariot', name='边车', en='Sidecar', glass='martini', base='cognac', baseName='干邑', ingredients={'干邑'}, color={r=0.85,g=0.55,b=0.2}, strength=4, gift=false, group='tarot', ability={ id='ab_chariot', name='冲锋', desc='强制庄家立即抽 2 张明牌，然后本局庄家停牌', target='B 强制庄家抽牌', special='dealer_draw_2_stop', interaction='instant', duration='round' } },
  { id='ck_justice', gddId='justice', name='萨泽拉克', en='Sazerac', glass='rocks', base='rye', baseName='黑麦威士忌', ingredients={'黑麦威士忌'}, color={r=0.75,g=0.4,b=0.1}, strength=4, gift=false, group='tarot', ability={ id='ab_justice', name='清算', desc='把本局牌堆按点数从小到大排序', target='C 改变牌堆构成', special='deck_sort_asc', interaction='instant', duration='round' } },
  { id='ck_hermit', gddId='hermit', name='高球', en='Highball', glass='highball', base='whiskey', baseName='威士忌', ingredients={'威士忌'}, color={r=0.85,g=0.7,b=0.3}, strength=2, gift=false, group='tarot', ability={ id='ab_hermit', name='独酌', desc='把牌堆顶 5 张沉到牌堆底', target='C 改变牌堆构成', special='sink_top_5', interaction='instant', duration='round' } },
  { id='ck_wheel', gddId='wheel', name='玛格丽特', en='Margarita', glass='coupe', base='tequila', baseName='龙舌兰', ingredients={'龙舌兰'}, color={r=0.9,g=0.9,b=0.4}, strength=3, gift=false, group='tarot', ability={ id='ab_wheel', name='轮转', desc='用模板重灌整副牌堆并重新洗牌', target='C 改变牌堆构成', special='deck_rebuild_shuffle', interaction='instant', duration='round' } },
  { id='ck_strength', gddId='strength', name='白俄罗斯', en='White Russian', glass='rocks', base='vodka', baseName='伏特加', ingredients={'伏特加'}, color={r=0.9,g=0.85,b=0.75}, strength=3, gift=false, group='tarot', ability={ id='ab_strength', name='蛮力', desc='强制庄家抽 1 张明牌，同时从你手牌随机抽 1 张塞给庄家当明牌', target='B 强制庄家抽牌', special='dealer_draw_1_give_random', interaction='instant', duration='round' } },
  { id='ck_hanged', gddId='hanged', name='僵尸', en='Zombie', glass='tiki', base='rum', baseName='朗姆', ingredients={'朗姆'}, color={r=0.5,g=0.3,b=0.1}, strength=4, gift=false, group='tarot', ability={ id='ab_hanged', name='悬挂', desc='把庄家点数最小的一张明牌与牌堆顶那张交换，不补牌', target='B 强制庄家抽牌', special='swap_dealer_lowest_with_draw', interaction='instant', duration='round' } },
  { id='ck_death', gddId='death', name='黑色俄罗斯', en='Black Russian', glass='rocks', base='vodka', baseName='伏特加', ingredients={'伏特加'}, color={r=0.1,g=0.05,b=0.05}, strength=3, gift=false, group='tarot', ability={ id='ab_death', name='终末', desc='强制庄家立即抽 3 张明牌', target='B 强制庄家抽牌', special='dealer_draw_3', interaction='instant', duration='round' } },
  { id='ck_temperance', gddId='temperance', name='龙舌兰日出', en='Tequila Sunrise', glass='highball', base='tequila', baseName='龙舌兰', ingredients={'龙舌兰'}, color={r=0.95,g=0.5,b=0.1}, strength=2, gift=false, group='tarot', ability={ id='ab_temperance', name='调和', desc='从本局牌堆里随机删掉 10 张', target='C 改变牌堆构成', special='deck_remove_random_10', interaction='instant', duration='round' } },
  { id='ck_devil', gddId='devil', name='飓风', en='Hurricane', glass='hurricane', base='rum', baseName='朗姆', ingredients={'朗姆'}, color={r=0.9,g=0.3,b=0.1}, strength=3, gift=false, group='tarot', ability={ id='ab_devil', name='诱引', desc='强制庄家抽 1 张明牌，且该张必为牌堆中点数最大的那张', target='B 强制庄家抽牌', special='dealer_draw_highest', interaction='instant', duration='round' } },
  { id='ck_tower', gddId='tower', name='巴黎之花', en='Perrier-Jouet', glass='flute', base='champagne', baseName='香槟', ingredients={'香槟'}, color={r=0.95,g=0.85,b=0.5}, strength=2, gift=false, group='tarot', ability={ id='ab_tower', name='崩塌', desc='强制庄家连续抽牌，直到其点数达到或超过 21（有张数上限防护）', target='B 强制庄家抽牌', special='dealer_draw_until_21', interaction='instant', duration='round' } },
  { id='ck_star', gddId='star', name='汤姆柯林斯', en='Tom Collins', glass='collins', base='gin', baseName='金酒', ingredients={'金酒'}, color={r=0.9,g=0.85,b=0.3}, strength=2, gift=false, group='tarot', ability={ id='ab_star', name='祈愿', desc='往本局牌堆插入 5 张 10 点牌', target='C 改变牌堆构成', special='deck_insert_5_tens', interaction='instant', duration='round' } },
  { id='ck_moon', gddId='moon', name='莫吉托', en='Mojito', glass='highball', base='rum', baseName='朗姆', ingredients={'朗姆'}, color={r=0.6,g=0.9,b=0.5}, strength=2, gift=false, group='tarot', ability={ id='ab_moon', name='潮汐', desc='为庄家补牌，直到明牌数与你的手牌数相同', target='A 改变庄家明牌数', special='dealer_fill_to_player_count', interaction='instant', duration='round' } },
  { id='ck_sun', gddId='sun', name='巴哈马妈妈', en='Bahama Mama', glass='highball', base='rum', baseName='朗姆', ingredients={'朗姆'}, color={r=0.95,g=0.6,b=0.1}, strength=3, gift=false, group='tarot', ability={ id='ab_sun', name='炽热', desc='为庄家每一张明牌各补 1 张（明牌数翻倍）', target='A 改变庄家明牌数', special='dealer_duplicate_ups', interaction='instant', duration='round' } },
  { id='ck_judgement', gddId='judgement', name='代基里', en='Daiquiri', glass='coupe', base='rum', baseName='朗姆', ingredients={'朗姆'}, color={r=0.9,g=0.95,b=0.8}, strength=3, gift=false, group='tarot', ability={ id='ab_judgement', name='末日', desc='把本局牌堆压缩为点数最大的一半', target='C 改变牌堆构成', special='deck_compress_top_half', interaction='instant', duration='round' } },
  { id='ck_world', gddId='world', name='皮斯科酸', en='Pisco Sour', glass='coupe', base='pisco', baseName='皮斯科', ingredients={'皮斯科'}, color={r=0.95,g=0.85,b=0.4}, strength=2, gift=false, group='tarot', ability={ id='ab_world', name='环球', desc='若庄家明牌不足 3 张，补发到 3 张', target='A 改变庄家明牌数', special='dealer_fill_to_3', interaction='instant', duration='round' } },
}
C.MAP = {}
for i = 1, #C.LIST do C.MAP[C.LIST[i].id] = C.LIST[i] end
function C.byId(id)
  if C.MAP[id] then return C.MAP[id] end
  for i = 1, #C.LIST do
    if C.LIST[i].gddId == id then return C.LIST[i] end
  end
  return nil
end
function C.count() return #C.LIST end
function C.giftPool()
  local out = {}
  for i = 1, #C.LIST do if C.LIST[i].gift then out[#out + 1] = C.LIST[i] end end
  return out
end
function C.bySpecial(sp)
  local out = {}
  for i = 1, #C.LIST do if C.LIST[i].ability.special == sp then out[#out + 1] = C.LIST[i] end end
  return out
end
return C
